---
- name: getting docker into system
  hosts: linux
  tasks:
    - name: Getting stuff
      apt:
        name: "{{ item }}"
        state: latest
      loop:
      - docker.io
      - pip
      - fontconfig 
      - openjdk-11-jre
      # - jenkins
      # - terraform

    - name: getting "python `docker`" for pulling images
      pip:
        name: docker
        state: latest

    - name: pull ELKF stack
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - kibana:8.1.1
        - elasticsearch:8.1.1
        - elastic/filebeat:8.1.1
        - logstash:8.1.1
  become: true


