#!/bin/bash


# running the last created image 
if [[ "$1" == "r" ]]; then
    run --rm --network p_net "$(sudo docker images -q |head -1)"
elif [[ "$1" == "rm" ]]; then
    # rm last image
    d rmi "$(sudo docker images -q |head -1)"
elif [[ "$1" == "upd" ]]; then
    go get -u all
elif [[ "$1" == "push" ]]; then
    git add . && \
    git commit -m "asd" && \
    git push &> /dev/null &
else
    # creating new image 
    CGO_ENABLED=0 go build . && \
    d build -t "$1" . && \
    run --rm --network p_net "$1"
exit; fi