#!/bin/bash


# curl -G https://api.github.com/search/code?q=sql%20is+repo:leatep/zet-notes 2>/dev/null | jq '.items | .[] | .path'

ido_commit () {
    read -r -p "Commit: " user_conf
    if [[ $user_conf == "y" ]]; then
        (cd "$ZET" &&
        git add ./"$date" &&
        git commit -m "add notes"
        git push 2> /dev/null &)
    fi
}

ido_status () {
    (cd "$ZET" &&
    git status)
}
# 
# ido_select () {
    # git_found="$(curl -G https://api.github.com/search/code?q=sql+repo:leatep/zet-notes 2>/dev/null | jq '.items | .[] | .path')"
    # for i in $git_found; do echo "$i"; done
    # echo "$git_found"
    var="$ZET/${var:1:-1}"
    head -1 < "$var"
# 
# }


if [[ $1 == "c" ]]; then
    date="$(date +"%Y%m_%d_%H%M%S")"
    folder="$ZET"/"$date"
    file="$folder/README.md"

    mkdir "$folder" &&
    touch "$file"
    if [[ $2 ]]; then
        printf "# %s" "$2" > "$file"
        fi
    vi "$file"
    
    ido_commit
elif [[ $1 == "st" ]]; then
    ido_status
elif [[ $1 == "sl" ]]; then
    ido_select
exit; fi



