#!/bin/bash

commit () {
    read -r -p "Commit: " user_conf
    if [[ $user_conf == "y" ]]; then
        (cd "$ZET" && \
        git add ./"$date" && \
        git commit -m "add stuff"
        git push 2> /dev/null &)
    fi
}


if [[ $1 == "c" ]]; then
    date="$(date +"%Y%m_%d_%H%M%S")"
    folder="$ZET"/"$date"
    file="$folder/README.md"

    mkdir "$folder" && \
    touch "$file"
    if [[ $2 ]]; then
        printf "# %s" "$2" > "$file"
        fi
    vi "$file"
    
    commit
exit; fi

if [[ $1 == "" ]]; then
    commit
exit; fi


