#!/bin/env python3
from os import environ
from sys import path, argv
from random import randint
from time import sleep

env = environ.get
path.append(env("GAME")) # my_whatever/game_docker
from sql.sql_query import psql


class give_loot:
    def __init__(self) -> None:
        self.cmd = psql().cmd
    
    def give(self):
        # get units that earned
        # give them xp and stuff, ig in proportion to the dmg they did 
        
        all_mobs = self.cmd('''select * from mobs
                            where hp = 0;''')
        for n in all_mobs.values():
            if n['hp'] == 0:
                unit = self.cmd('''update worker_info
                         set xp = xp + 10
                         where id = 1
                         returning *;''')
                print(f"xp + 10, total {unit[0]['xp']}")
                
                self.cmd(f'''delete from mobs
                         where id = {n['id']}
                         returning *;''')
            
        

        



if __name__ == "__main__":
    give_loot().give()


