#!/bin/env python3
from os import environ
from sys import path, argv
from random import randint
from time import sleep

env = environ.get
path.append(env("GAME")) # my_whatever/game_docker
from sql.sql_query import psql


class give_loot:
    def __init__(self) -> None:
        self.cmd = psql().cmd
    
    def give(self):
        # get units that earned
        # give them xp and stuff, ig in proportion to the dmg they did 
        
        all_mobs = self.get_dead_mobs()
        
        for n in all_mobs.values():
            if n['hp'] == 0:
                
                self.give_xp(1, 10)
                id = n['id']
                
                self.delete_mob(id)
            
        
    def get_dead_mobs(self):
        return self.cmd('''select * from mobs where hp = 0''')

    def give_xp(self, id: int, xp: int = 10):
        unit = self.cmd(f'''update worker_info
                 set xp = xp + {xp}
                 where id = {id}
                 returning *;''')
        
        print(f"xp + 10, total {unit[0]['xp']}")
        return True

    def delete_mob(self, id: int):
        self.cmd(f'''delete from mobs
                 where id = {id}
                 returning *;''')


if __name__ == "__main__":
    give_loot().give()


