#!/bin/env python3

from os import environ
from sys import argv, path
from wrap import init_conn
env = environ.get


path.append(env("GAME")) # my_whatever/game_docker
from sql.sql_query import psql
from hub.wrap import init_conn


def get_inv(cmd):
    inventory = cmd("""select * from items;""")
    
    if len(argv) > 1:
        try:
            for n in inventory:
                if inventory[n]['name'] == argv[1]:
                    print(f"{argv[1]}: {inventory[n]['amount']}")
        except (Exception, KeyError) as error:
            print(error)
    else:
        [print(f"{inventory[n]['name']}: {inventory[n]['amount']}") for n in inventory]


if __name__ == "__main__":
    init_conn(get_inv)
        






