#!/bin/env python3

from os import environ
from sys import argv, path
env = environ.get


path.append(env("GAME")) # my_whatever/game_docker
from sql.sql_query import psql
from colors import fg_rgb

class fetch_data():
    def __init__(self) -> None:
        self.p = psql()

        self.cmd = "select * from items"
        self.cmd += f" where name = '{argv[1]}'" if len(argv) > 1 else ''
        self.cmd += ';'

    def get_inv(self):
        try:

            self.p.exec(self.cmd)
            fetched_data = self.p.fetch_dict()

            for item in fetched_data.values():
                item_name, item_amount = str(item['name']), str(item['amount'])

                text_line = f'{item_name}: {item_amount}'
                print(fg_rgb(text_line))

        except (Exception) as error:
            print(error.args)

if __name__ == "__main__":
    fetch_data().get_inv()






