#!/bin/env python3
from os import environ
from sys import argv, path

env = environ.get

path.append(env("GAME")) # my_whatever/game_docker
from sql.sql_query import psql

class work_class:
    def __init__(self) -> None:
        self.p = psql()
        self.req_resource = 'Rock'
        self.summom_cost = 10
    
    def start_work(self):
        try:
            cmd = f'''update items 
            set amount = amount - {self.summom_cost} 
            where name = '{self.req_resource}' 
            returning amount;'''
            self.p.exec(cmd); self.p.commit()
            amount = self.p.fetch_dict()
            
            print('Your balance:', amount[0]['amount'])
            
            self.p.exec('''insert into worker (name) 
                                values ('Human') 
                                returning id, name, grade, level, job;''')
            self.p.commit()
            worker = self.p.fetch_dict()
            
            self.p.exec(f'''insert into worker_info (worker_id)
                              values ({worker[0]['id']})
                              returning *;''')
            self.p.commit()
            worker_info = self.p.fetch_dict()
            
            [print(f"{i}: {worker[0][i]}") for i in worker[0]]
            print(worker_info)
        except (Exception) as error:
            print(error.args)
 
 

    def check_stock(self):
        try:
            check_quantity = self.p.exec('''select amount from items
                                 where name = 'Rock';''')
            for n in check_quantity:
                if check_quantity[n]['amount'] < self.summon_cost:
                    print('you dont have enough materials')
        
        except Exception:
            pass
        
        
if __name__ == "__main__":
    work_class().start_work()
    
