#!/bin/env python3
from os import environ
from sys import argv, path

env = environ.get

path.append(env("GAME")) # my_whatever/game_docker
from hub.wrap import init_conn



def start_work(cmd):
    summon_cost = 10
    check_quantity = cmd('''select amount from items
                         where name = 'Rock';''')
    for n in check_quantity:
        if check_quantity[n]['amount'] < summon_cost:
            break
        
    updated_amount = cmd(f'''update items
        set amount = amount - {summon_cost}
        where name = 'Rock'
        returning amount;''')
    print(updated_amount)
    worker = cmd('''insert into worker (name) 
                 values ('Human') 
                 returning *;''')
    for n in worker:
        [print(f"{i}: {worker[n][i]}") for i in worker[n]]

            
            
        
if __name__ == "__main__":
    init_conn(start_work)
    