#!/bin/env bash

ff () {
for i in $(sudo docker ps -q); do
    sudo docker inspect -f \
    '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}} [{{.Config.Hostname}} {{.Config.Image}}]' "$i";
done
}

ff