#!/usr/bin/env bash



fn () {
if test "$1" = "n"; then
    sudo docker container ls \
        --format 'table {{.ID}}\t{{.Image}}\t{{.Networks}}';
    exit; fi

if test "$1" = "p"; then
    sudo docker container ls \
        --format 'table {{.ID}}\t{{.Image}}\t{{.Ports}}';
    exit; fi

sudo docker container ls \
    --format 'table {{.ID}}\t{{.Image}}\t{{.Names}}'
}
fn "$@"