#!/bin/env python3
from os import environ
from sys import path, argv, flags
from random import randint
from time import sleep
from collections import defaultdict

env = environ.get
path.append(env("GAME")) # my_whatever/game_docker
from sql.sql_query import psql

# creating separate container that 
# - manage unit of the attacker

# action 1: getting unit data, 
# action 2: stating that unit is busy, and add container_id
# action 3: exec query that takes att from unit and attack mob
# action 4: if unit survive and mob is dead, generate loot

class battle:
    def __init__(self, unit_id, enemy_id) -> None:
        self.p = psql()
        
        self.unit_id = unit_id
        self.enemy_id = enemy_id
    
    def start(self) -> None:
        while True:
            unit = self.get_units_data('unit')
            enemy = self.get_units_data('enemy')
            
            if unit['hp'] <= 0 or enemy['hp'] <= 0:
                break
            
            unit = self.attack_('unit')
            enemy = self.attack_('enemy')                        

            print(f"unit_hp: {unit['hp']}/{unit['max_hp']}")
            print(f"enemy_hp: {enemy['hp']}/{enemy['max_hp']}")

    def get_units_data(self, mod: str):
        if mod == 'unit':
            self.p.exec(f'''select * from worker_info
                    where id = {self.unit_id};''')
            return self.p.fetch_dict()[0]
        
        elif mod == 'enemy':
            self.p.exec(f'''select * from mobs
                    where id = {self.enemy_id};''')
            return self.p.fetch_dict()[0]

    def attack_(self, mod):
        if mod == 'unit':
            self.p.exec(f'''update worker_info
                set hp = hp - (select attack from mobs where id = {self.enemy_id})
                where id = {self.unit_id}
                returning *;''')
            self.p.commit()
            return self.p.fetch_dict()[0]
            
        elif mod == 'enemy':
            self.p.exec(f'''update mobs
                set hp = hp - (select attack from worker_info where id = {self.unit_id})
                where id = {self.enemy_id}
                returning *;''')
            self.p.commit()
            return self.p.fetch_dict()[0]


if __name__ == "__main__":
    b1 = battle(argv[1], argv[2])
    b1.start()


