#!/bin/env bash

net="p_net"
name="game123"

# DGAME="Project clone location at the end: '/my_whatever/game_docker'"

sudo docker run -it --rm \
    --name "$name" \
    --network "$net" \
    -v "$DGAME":game \
    game
