#!/bin/env python3

TODO 1: think what can be mined at first
TODO 2: complete random mechanism
TODO 3: complete random of rarity (for workers and ore)
TODO 4: make enemy and make basic battle 
TODO 5: make xp 
